### ISSUE TITLE
蜡烛图和成交量没有上下对齐

### ISSUE THREAD

**Issue by wuxianliang** [2557606319/H5-Kline#4]
首先感谢你分享这个工作,有一个细节需要调整.蜡烛图和成交量没有对齐.
对比

[官方示例 ](https://ecomfe.github.io/echarts-examples/public/editor.html?c=candlestick-brush)

发现成交量那一行起始位置不一样,但是我没有找到修改哪个参数.

**Comment by netwhale2019** [comment]
好的 感谢你的反馈 ，后续有时间会把他修复的

**Comment by allanlau1988** [comment]
还有分时图 开始的时候 9:30  好像只有 :30  谢谢楼主的分享

**Comment by zliyk** [comment]
> 首先感谢你分享这个工作,有一个细节需要调整.蜡烛图和成交量没有对齐.
> 对比
> 
> [官方示例 ](https://ecomfe.github.io/echarts-examples/public/editor.html?c=candlestick-brush)
> 
> 发现成交量那一行起始位置不一样,但是我没有找到修改哪个参数.

//boundaryGap: false
注释这句好像就可以了
